
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: system
spec:
  ports:
    - port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    control-plane: controller-manager
